language: php
php:
  - 7.2

sudo: false

services:
  - mysql

env:
  global:
    - PLUGIN_NAME=FroshWebP

cache:
  directories:
    - "${HOME}/.composer/cache/files"

install:
  - composer install

script:
  - "./build.sh $TRAVIS_TAG"

stages:
  - test
  - name: Store-Check
    if: branch = master
  - name: Store-Sync
    if: branch = master
  - name: Store-Deploy
    if: tag IS present

jobs:
  include:
    - stage: Store-Check
      php: 7.3
      before_script: skip
      install:
        - ./build.sh master
        - wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/0.1.1/frosh-plugin-upload.phar' -O frosh-plugin-upload.phar
      script:
        - php frosh-plugin-upload.phar plugin:validate ${TRAVIS_BUILD_DIR}/${PLUGIN_NAME}*.zip
    - stage: Store-Sync
      before_script: skip
      php: 7.3
      install:
        - wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/0.1.1/frosh-plugin-upload.phar' -O frosh-plugin-upload.phar
      script:
        - php frosh-plugin-upload.phar plugin:update ${TRAVIS_BUILD_DIR}/Resources/store
    - stage: Store-Deploy
      before_script: skip
      php: 7.3
      install:
        - wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/0.1.1/frosh-plugin-upload.phar' -O frosh-plugin-upload.phar
      script:
        - ./build.sh
        - php frosh-plugin-upload.phar plugin:upload ${TRAVIS_BUILD_DIR}/${PLUGIN_NAME}*.zip

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: j9cymvEpD83VYj2+2Gq6vnVIArkoKId1/cuiLQdatZi+FL37Bf/Y26H7eQ0fkhOxGSVcUNJ2t8C6bw+ZFYaLw7Gy6TB9ysDWJCP1bMOYixfNWAlDrfbSz2eItK5XsCr3hVUrTarl1iCQRvxGp3ZK+skrtO0pIQ8Vo5J7Rk8Ot3TQhILR8FV5AwjirBibCB/4XTTrNxNxzshB3e3sD+Wq7OXJzmpV8F7M1ctJQnoCCurTveF27/D9VLw45khpKkQL3WDIPcCPsvtVqwWtkMd7B0ab1FR/J/gZTfTLD2la+NCw77+VfQClY0jVp2o+Q+ELi2i+/FwUSNVpsB3ecWITRqpKey8GcppV1p+U5i+XKeoHlUtubjHfpszLbU6qArtC178H73t8l3pp8Mg53ZrIF1e13S7jW7YGx8RlYk5g1G6vUPEODoV+S4UTOxfAHiB91wi5/B0TIfAY+65UL/lNJ8SpUQwhlLbGjW/PAk98RSxoDOsEyoOXIerqd1qRki8tBcav5nxSQl7Y9maP4jlis0rtcovM/ClUnLfTmXS6S5GOH7u/qe17J6nTsL1/BZ19n6NJV7hjXCjTvrIPrUNL+e+gyHn/fGS8gNKl60ICMNEuJ8/L2eORi5s6Jr9qKu2c0ZnLhqnf+199noG9fYI3nG+PjBVWu4qGbBe46rebnEY=
  file_glob: true
  file: FroshWebP*.zip
  on:
    repo: FriendsOfShopware/FroshWebP
    tags: true
